# Generated by Django 5.1.2 on 2026-08-12 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_cssrule_html_user_best_score_user_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='FinalSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_no', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField()),
                ('final_css', models.TextField()),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('total', models.PositiveSmallIntegerField(default=0)),
                ('reached_all', models.BooleanField(default=False)),
                ('design_mode', models.BooleanField(default=False)),
                ('eligible', models.BooleanField(default=False)),
                ('hints_used', models.PositiveSmallIntegerField(default=0)),
                ('objectives_hinted', models.PositiveSmallIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_submission', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'final submission',
                'verbose_name_plural': 'final submissions',
                'ordering': ('-submitted_at',),
            },
        ),
        migrations.CreateModel(
            name='HintReveal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.CharField(max_length=64)),
                ('level', models.PositiveSmallIntegerField()),
                ('revealed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hint_reveals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('revealed_at', 'id'),
                'unique_together': {('user', 'objective', 'level')},
            },
        ),
    ]
